# This is a TOML configuration file.

# Connection details of a Electrum Server.
[electrum]
  ServerHost  = "electrumx-server.tbtc.svc.cluster.local"
  ServerPort  = "50002"

# Connection details for Block Cypher API.
[blockcypher]
  Token   = "d195ca15455f42b7842abd7c691191c9"
  Coin    = "btc"
  Chain   = "test3"

# Connection details of ethereum blockchain.
[ethereum]
  URL                 = "Set by Kube"
  PrivateKey          = "Set by Kube"

# Addresses of contracts deployed on ethereum blockchain.
[ethereum.ContractAddresses]
  TBTCSystem = "Set by Kube"